export const Paises = [
    { id: "1", text: "Andorra" },
    { id: "2", text: "Emiratos Árabes Unidos" },
    { id: "3", text: "Afganistán" },
    { id: "4", text: "Antigua y Barbuda" },
    { id: "5", text: "Anguila" },
    { id: "6", text: "Albania" },
    { id: "7", text: "Armenia" },
    { id: "8", text: "Antillas Neerlandesas" },
    { id: "9", text: "Angola" },
    { id: "10", text: "Antártida" },
    { id: "11", text: "Argentina" },
    { id: "12", text: "Samoa Americana" },
    { id: "13", text: "Austria" },
    { id: "14", text: "Australia" },
    { id: "15", text: "Aruba" },
    { id: "16", text: "Islas Áland" },
    { id: "17", text: "Azerbaiyán" },
    { id: "18", text: "Bosnia y Herzegovina" },
    { id: "19", text: "Barbados" },
    { id: "20", text: "Bangladesh" },
    { id: "21", text: "Bélgica" },
    { id: "22", text: "Burkina Faso" },
    { id: "23", text: "Bulgaria" },
    { id: "24", text: "Bahréin" },
    { id: "25", text: "Burundi" },
    { id: "26", text: "Benin" },
    { id: "27", text: "San Bartolomé" },
    { id: "28", text: "Bermudas" },
    { id: "29", text: "Brunéi" },
    { id: "30", text: "Bolivia" },
    { id: "31", text: "Brasil" },
    { id: "32", text: "Bahamas" },
    { id: "33", text: "Bhután" },
    { id: "34", text: "Isla Bouvet" },
    { id: "35", text: "Botsuana" },
    { id: "36", text: "Belarús" },
    { id: "37", text: "Belice" },
    { id: "38", text: "Canadá" },
    { id: "39", text: "Islas Cocos" },
    { id: "40", text: "República Centro-Africana" },
    { id: "41", text: "Congo" },
    { id: "42", text: "Suiza" },
    { id: "43", text: "Costa de Marfil" },
    { id: "44", text: "Islas Cook" },
    { id: "45", text: "Chile" },
    { id: "46", text: "Camerún" },
    { id: "47", text: "China" },
    { id: "48", text: "Colombia" },
    { id: "49", text: "Costa Rica" },
    { id: "50", text: "Cuba" },
    { id: "51", text: "Cabo Verde" },
    { id: "52", text: "Islas Christmas" },
    { id: "53", text: "Chipre" },
    { id: "54", text: "República Checa" },
    { id: "55", text: "Alemania" },
    { id: "56", text: "Yibuti" },
    { id: "57", text: "Dinamarca" },
    { id: "58", text: "Domínica" },
    { id: "59", text: "República Dominicana" },
    { id: "60", text: "Argel" },
    { id: "61", text: "Ecuador" },
    { id: "62", text: "Estonia" },
    { id: "63", text: "Egipto" },
    { id: "64", text: "Sahara Occidental" },
    { id: "65", text: "Eritrea" },
    { id: "66", text: "España" },
    { id: "67", text: "Etiopía" },
    { id: "68", text: "Finlandia" },
    { id: "69", text: "Fiji" },
    { id: "70", text: "Islas Malvinas" },
    { id: "71", text: "Micronesia" },
    { id: "72", text: "Islas Faroe" },
    { id: "73", text: "Francia" },
    { id: "74", text: "Gabón" },
    { id: "75", text: "Reino Unido" },
    { id: "76", text: "Granada" },
    { id: "77", text: "Georgia" },
    { id: "78", text: "Guayana Francesa" },
    { id: "79", text: "Guernsey" },
    { id: "80", text: "Ghana" },
    { id: "81", text: "Gibraltar" },
    { id: "82", text: "Groenlandia" },
    { id: "83", text: "Gambia" },
    { id: "84", text: "Guinea" },
    { id: "85", text: "Guadalupe" },
    { id: "86", text: "Guinea Ecuatorial" },
    { id: "87", text: "Grecia" },
    {
      id: "88",
      text: "Georgia del Sur e Islas Sandwich del Sur",
    },
    { id: "89", text: "Guatemala" },
    { id: "90", text: "Guam" },
    { id: "91", text: "Guinea-Bissau" },
    { id: "92", text: "Guayana" },
    { id: "93", text: "Hong Kong" },
    { id: "94", text: "Islas Heard y McDonald" },
    { id: "95", text: "Honduras" },
    { id: "96", text: "Croacia" },
    { id: "97", text: "Haití" },
    { id: "98", text: "Hungría" },
    { id: "99", text: "Indonesia" },
    { id: "100", text: "Irlanda" },
    { id: "101", text: "Israel" },
    { id: "102", text: "Isla de Man" },
    { id: "103", text: "India" },
    {
      id: "104",
      text: "Territorio Británico del Océano Índico",
    },
    { id: "105", text: "Irak" },
    { id: "106", text: "Irán" },
    { id: "107", text: "Islandia" },
    { id: "108", text: "Italia" },
    { id: "109", text: "Jersey" },
    { id: "110", text: "Jamaica" },
    { id: "111", text: "Jordania" },
    { id: "112", text: "Japón" },
    { id: "113", text: "Kenia" },
    { id: "114", text: "Kirguistán" },
    { id: "115", text: "Camboya" },
    { id: "116", text: "Kiribati" },
    { id: "117", text: "Comoros" },
    { id: "118", text: "San Cristóbal y Nieves" },
    { id: "119", text: "Corea del Norte" },
    { id: "120", text: "Corea del Sur" },
    { id: "121", text: "Kuwait" },
    { id: "122", text: "Islas Caimán" },
    { id: "123", text: "Kazajstán" },
    { id: "124", text: "Laos" },
    { id: "125", text: "Líbano" },
    { id: "126", text: "Santa Lucía" },
    { id: "127", text: "Liechtenstein" },
    { id: "128", text: "Sri Lanka" },
    { id: "129", text: "Liberia" },
    { id: "130", text: "Lesotho" },
    { id: "131", text: "Lituania" },
    { id: "132", text: "Luxemburgo" },
    { id: "133", text: "Letonia" },
    { id: "134", text: "Libia" },
    { id: "135", text: "Marruecos" },
    { id: "136", text: "Mónaco" },
    { id: "137", text: "Moldova" },
    { id: "138", text: "Montenegro" },
    { id: "139", text: "Madagascar" },
    { id: "140", text: "Islas Marshall" },
    { id: "141", text: "Macedonia" },
    { id: "142", text: "Mali" },
    { id: "143", text: "Myanmar" },
    { id: "144", text: "Mongolia" },
    { id: "145", text: "Macao" },
    { id: "146", text: "Martinica" },
    { id: "147", text: "Mauritania" },
    { id: "148", text: "Montserrat" },
    { id: "149", text: "Malta" },
    { id: "150", text: "Mauricio" },
    { id: "151", text: "Maldivas" },
    { id: "152", text: "Malawi" },
    { id: "153", text: "México" },
    { id: "154", text: "Malasia" },
    { id: "155", text: "Mozambique" },
    { id: "156", text: "Namibia" },
    { id: "157", text: "Nueva Caledonia" },
    { id: "158", text: "Níger" },
    { id: "159", text: "Islas Norkfolk" },
    { id: "160", text: "Nigeria" },
    { id: "161", text: "Nicaragua" },
    { id: "162", text: "Países Bajos" },
    { id: "163", text: "Noruega" },
    { id: "164", text: "Nepal" },
    { id: "165", text: "Nauru" },
    { id: "166", text: "Niue" },
    { id: "167", text: "Nueva Zelanda" },
    { id: "168", text: "Omán" },
    { id: "169", text: "Panamá" },
    { id: "170", text: "Perú" },
    { id: "171", text: "Polinesia Francesa" },
    { id: "172", text: "Papúa Nueva Guinea" },
    { id: "173", text: "Filipinas" },
    { id: "174", text: "Pakistán" },
    { id: "175", text: "Polonia" },
    { id: "176", text: "San Pedro y Miquelón" },
    { id: "177", text: "Islas Pitcairn" },
    { id: "178", text: "Puerto Rico" },
    { id: "179", text: "Palestina" },
    { id: "180", text: "Portugal" },
    { id: "181", text: "Islas Palaos" },
    { id: "182", text: "Paraguay" },
    { id: "183", text: "Qatar" },
    { id: "184", text: "Reunión" },
    { id: "185", text: "Rumanía" },
    { id: "186", text: "Serbia y Montenegro" },
    { id: "187", text: "Rusia" },
    { id: "188", text: "Ruanda" },
    { id: "189", text: "Arabia Saudita" },
    { id: "190", text: "Islas Solomón" },
    { id: "191", text: "Seychelles" },
    { id: "192", text: "Sudán" },
    { id: "193", text: "Suecia" },
    { id: "194", text: "Singapur" },
    { id: "195", text: "Santa Elena" },
    { id: "196", text: "Eslovenia" },
    { id: "197", text: "Islas Svalbard y Jan Mayen" },
    { id: "198", text: "Eslovaquia" },
    { id: "199", text: "Sierra Leona" },
    { id: "200", text: "San Marino" },
    { id: "201", text: "Senegal" },
    { id: "202", text: "Somalia" },
    { id: "203", text: "Surinam" },
    { id: "204", text: "Santo Tomé y Príncipe" },
    { id: "205", text: "El Salvador" },
    { id: "206", text: "Siria" },
    { id: "207", text: "Suazilandia" },
    { id: "208", text: "Islas Turcas y Caicos" },
    { id: "209", text: "Chad" },
    { id: "210", text: "Territorios Australes Franceses" },
    { id: "211", text: "Togo" },
    { id: "212", text: "Tailandia" },
    { id: "213", text: "Tanzania" },
    { id: "214", text: "Tayikistán" },
    { id: "215", text: "Tokelau" },
    { id: "216", text: "Timor-Leste" },
    { id: "217", text: "Turkmenistán" },
    { id: "218", text: "Túnez" },
    { id: "219", text: "Tonga" },
    { id: "220", text: "Turquía" },
    { id: "221", text: "Trinidad y Tobago" },
    { id: "222", text: "Tuvalu" },
    { id: "223", text: "Taiwán" },
    { id: "224", text: "Ucrania" },
    { id: "225", text: "Uganda" },
    { id: "226", text: "Estados Unidos de América" },
    { id: "227", text: "Uruguay" },
    { id: "228", text: "Uzbekistán" },
    { id: "229", text: "Ciudad del Vaticano" },
    { id: "230", text: "San Vicente y las Granadinas" },
    { id: "231", text: "Venezuela" },
    { id: "232", text: "Islas Vírgenes Britán" },
  ]
export const Nacionalidad = [
        { value: '1', text: 'AD' },
        { value: '2', text: 'AE' },
        { value: '3', text: 'AF' },
        { value: '4', text: 'AG' },
        { value: '5', text: 'AI' },
        { value: '6', text: 'AL' },
        { value: '7', text: 'AM' },
        { value: '8', text: 'AN' },
        { value: '9', text: 'AO' },
        { value: '10', text: 'AQ' },
        { value: '11', text: 'AR' },
        { value: '12', text: 'AS' },
        { value: '13', text: 'AT' },
        { value: '14', text: 'AU' },
        { value: '15', text: 'AW' },
        { value: '16', text: 'AX' },
        { value: '17', text: 'AZ' },
        { value: '18', text: 'BA' },
        { value: '19', text: 'BB' },
        { value: '20', text: 'BD' },
        { value: '21', text: 'BE' },
        { value: '22', text: 'BF' },
        { value: '23', text: 'BG' },
        { value: '24', text: 'BH' },
        { value: '25', text: 'BI' },
        { value: '26', text: 'BJ' },
        { value: '27', text: 'BL' },
        { value: '28', text: 'BM' },
        { value: '29', text: 'BN' },
        { value: '30', text: 'BO' },
        { value: '31', text: 'BR' },
        { value: '32', text: 'BS' },
        { value: '33', text: 'BT' },
        { value: '34', text: 'BV' },
        { value: '35', text: 'BW' },
        { value: '36', text: 'BY' },
        { value: '37', text: 'BZ' },
        { value: '38', text: 'CA' },
        { value: '39', text: 'CC' },
        { value: '40', text: 'CF' },
        { value: '41', text: 'CG' },
        { value: '42', text: 'CH' },
        { value: '43', text: 'CI' },
        { value: '44', text: 'CK' },
        { value: '45', text: 'CL' },
        { value: '46', text: 'CM' },
        { value: '47', text: 'CN' },
        { value: '48', text: 'CO' },
        { value: '49', text: 'CR' },
        { value: '50', text: 'CU' },
        { value: '51', text: 'CV' },
        { value: '52', text: 'CX' },
        { value: '53', text: 'CY' },
        { value: '54', text: 'CZ' },
        { value: '55', text: 'DE' },
        { value: '56', text: 'DJ' },
        { value: '57', text: 'DK' },
        { value: '58', text: 'DM' },
        { value: '59', text: 'DO' },
        { value: '60', text: 'DZ' },
        { value: '61', text: 'EC' },
        { value: '62', text: 'EE' },
        { value: '63', text: 'EG' },
        { value: '64', text: 'EH' },
        { value: '65', text: 'ER' },
        { value: '66', text: 'ES' },
        { value: '67', text: 'ET' },
        { value: '68', text: 'FI' },
        { value: '69', text: 'FJ' },
        { value: '70', text: 'FK' },
        { value: '71', text: 'FM' },
        { value: '72', text: 'FO' },
        { value: '73', text: 'FR' },
        { value: '74', text: 'GA' },
        { value: '75', text: 'GB' },
        { value: '76', text: 'GD' },
        { value: '77', text: 'GE' },
        { value: '78', text: 'GF' },
        { value: '79', text: 'GG' },
        { value: '80', text: 'GH' },
        { value: '81', text: 'GI' },
        { value: '82', text: 'GL' },
        { value: '83', text: 'GM' },
        { value: '84', text: 'GN' },
        { value: '85', text: 'GP' },
        { value: '86', text: 'GQ' },
        { value: '87', text: 'GR' },
        { value: '88', text: 'GS' },
        { value: '89', text: 'GT' },
        { value: '90', text: 'GU' },
        { value: '91', text: 'GW' },
        { value: '92', text: 'GY' },
        { value: '93', text: 'HK' },
        { value: '94', text: 'HM' },
        { value: '95', text: 'HN' },
        { value: '96', text: 'HR' },
        { value: '97', text: 'HT' },
        { value: '98', text: 'HU' },
        { value: '99', text: 'ID' },
        { value: '100', text: 'IE' },
        { value: '101', text: 'IL' },
        { value: '102', text: 'IM' },
        { value: '103', text: 'IN' },
        { value: '104', text: 'IO' },
        { value: '105', text: 'IQ' },
        { value: '106', text: 'IR' },
        { value: '107', text: 'IS' },
        { value: '108', text: 'IT' },
        { value: '109', text: 'JE' },
        { value: '110', text: 'JM' },
        { value: '111', text: 'JO' },
        { value: '112', text: 'JP' },
        { value: '113', text: 'KE' },
        { value: '114', text: 'KG' },
        { value: '115', text: 'KH' },
        { value: '116', text: 'KI' },
        { value: '117', text: 'KM' },
        { value: '118', text: 'KN' },
        { value: '119', text: 'KP' },
        { value: '120', text: 'KR' },
        { value: '121', text: 'KW' },
        { value: '122', text: 'KY' },
        { value: '123', text: 'KZ' },
        { value: '124', text: 'LA' },
        { value: '125', text: 'LB' },
        { value: '126', text: 'LC' },
        { value: '127', text: 'LI' },
        { value: '128', text: 'LK' },
        { value: '129', text: 'LR' },
        { value: '130', text: 'LS' },
        { value: '131', text: 'LT' },
        { value: '132', text: 'LU' },
        { value: '133', text: 'LV' },
        { value: '134', text: 'LY' },
        { value: '135', text: 'MA' },
        { value: '136', text: 'MC' },
        { value: '137', text: 'MD' },
        { value: '138', text: 'ME' },
        { value: '139', text: 'MG' },
        { value: '140', text: 'MH' },
        { value: '141', text: 'MK' },
        { value: '142', text: 'ML' },
        { value: '143', text: 'MM' },
        { value: '144', text: 'MN' },
        { value: '145', text: 'MO' },
        { value: '146', text: 'MQ' },
        { value: '147', text: 'MR' },
        { value: '148', text: 'MS' },
        { value: '149', text: 'MT' },
        { value: '150', text: 'MU' },
        { value: '151', text: 'MV' },
        { value: '152', text: 'MW' },
        { value: '153', text: 'MX' },
        { value: '154', text: 'MY' },
        { value: '155', text: 'MZ' },
        { value: '156', text: 'NA' },
        { value: '157', text: 'NC' },
        { value: '158', text: 'NE' },
        { value: '159', text: 'NF' },
        { value: '160', text: 'NG' },
        { value: '161', text: 'NI' },
        { value: '162', text: 'NL' },
        { value: '163', text: 'NO' },
        { value: '164', text: 'NP' },
        { value: '165', text: 'NR' },
        { value: '166', text: 'NU' },
        { value: '167', text: 'NZ' },
        { value: '168', text: 'OM' },
        { value: '169', text: 'PA' },
        { value: '170', text: 'PE' },
        { value: '171', text: 'PF' },
        { value: '172', text: 'PG' },
        { value: '173', text: 'PH' },
        { value: '174', text: 'PK' },
        { value: '175', text: 'PL' },
        { value: '176', text: 'PM' },
        { value: '177', text: 'PN' },
        { value: '178', text: 'PR' },
        { value: '179', text: 'PS' },
        { value: '180', text: 'PT' },
        { value: '181', text: 'PW' },
        { value: '182', text: 'PY' },
        { value: '183', text: 'QA' },
        { value: '184', text: 'RE' },
        { value: '185', text: 'RO' },
        { value: '186', text: 'RS' },
        { value: '187', text: 'RU' },
        { value: '188', text: 'RW' },
        { value: '189', text: 'SA' },
        { value: '190', text: 'SB' },
        { value: '191', text: 'SC' },
        { value: '192', text: 'SD' },
        { value: '193', text: 'SE' },
        { value: '194', text: 'SG' },
        { value: '195', text: 'SH' },
        { value: '196', text: 'SI' },
        { value: '197', text: 'SJ' },
        { value: '198', text: 'SK' },
        { value: '199', text: 'SL' },
        { value: '200', text: 'SM' },
        { value: '201', text: 'SN' },
        { value: '202', text: 'SO' },
        { value: '203', text: 'SR' },
        { value: '204', text: 'ST' },
        { value: '205', text: 'SV' },
        { value: '206', text: 'SY' },
        { value: '207', text: 'SZ' },
        { value: '208', text: 'TC' },
        { value: '209', text: 'TD' },
        { value: '210', text: 'TF' },
        { value: '211', text: 'TG' },
        { value: '212', text: 'TH' },
        { value: '213', text: 'TH' },
        { value: '214', text: 'TJ' },
        { value: '215', text: 'TK' },
        { value: '216', text: 'TL' },
        { value: '217', text: 'TM' },
        { value: '218', text: 'TN' },
        { value: '219', text: 'TO' },
        { value: '220', text: 'TR' },
        { value: '221', text: 'TT' },
        { value: '222', text: 'TV' },
        { value: '223', text: 'TW' },
        { value: '224', text: 'UA' },
        { value: '225', text: 'UG' },
        { value: '226', text: 'US' },
        { value: '227', text: 'UY' },
        { value: '228', text: 'UZ' },
        { value: '229', text: 'VA' },
        { value: '230', text: 'VC' },
        { value: '231', text: 'VE' },
        { value: '232', text: 'VG' },
        { value: '233', text: 'VI' },
        { value: '234', text: 'VN' },
        { value: '235', text: 'VU' },
        { value: '236', text: 'WF' },
        { value: '237', text: 'WS' },
        { value: '238', text: 'YE' },
        { value: '239', text: 'YT' },
        { value: '240', text: 'ZA' }

]
export const estadoCivil = [
  
    { text: "SOLTERO (A)", id: 1 },
    { text: "CASADO (A)", id: 2 },
    { text: "DIVORCIADO (A)", id: 3 },
    { text: "VIUDO (A)", id: 4 },
    { text: "CONCUBINA/CONCUBINARIO/UNIÓN LIBRE", id: 5 },
    { text: "SOCIEDAD DE CONVIVENCIA", id: 6 },
  
]
export const Regimenes = [
  
    { text: "SOCIEDAD CONYUGAL", id: 1 },
    { text: "SEPARACIÓN DE BIENES", id: 2 },
    { text: "OTRO", id: 3 },
  
]